version: "3.8"
services:
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
    depends_on:
      - server

  server:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "4000:4000"
    environment:
      REFRESH_TOKEN_SECRET: 9ae90761-92eb-4d39-90f4-6c862c19394a
      ACCESS_TOKEN_SECRET: 7438940c-8b4d-47ec-8e0a-9b1f427e25e2
      DB_HOST: db
    depends_on:
      - db
  db:
    image: postgres:15.4-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: prodcom_e
    volumes:
      - prodcom_e:/var/lib/postgresql/data
volumes:
  prodcom_e:
    driver: local
