version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '4000:4000'
    # volumes:
    #   - './backend:/app'
    #   - '/app/node_modules'
    environment:
      REFRESH_TOKEN_SECRET: 9ae90761-92eb-4d39-90f4-6c862c19394a
      ACCESS_TOKEN_SECRET: 7438940c-8b4d-47ec-8e0a-9b1f427e25e2
      # POSTGRES_DB_URI: postgres://postgres:postgres@db:5432/prodcom_e
      DB_HOST: db
      # DB_USER: postgres
      # DB_PASSWORD: postgres
      # DB_NAME: prodcom_e
      CHOKIDAR_USEPOLLING: true
      WATCHPACK_POLLING: true
    depends_on:
      - db
  db:
    image: postgres:15.4-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: prodcom_e
    volumes:
      - prodcom_e:/var/lib/postgresql/data
volumes:
  prodcom_e:
    driver: local
