apiVersion: v1
kind: ConfigMap
metadata:
  name: ecom-config
  namespace: ecom
data:
  ENV: "production"
  PORT: "4000"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_DB_CACHE: "0"
  REDIS_DB_RATELIMIT: "1"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  CACHE_TTL_PRODUCT: "300"
  CACHE_TTL_CATEGORY: "600"
  REFRESH_TOKEN_NAME: qid
  REFRESH_TOKEN_EXPIREDIN: 3d

  ACCESS_TOKEN_NAME: jid
  ACCESS_TOKEN_EXPIREDIN: 3d
